colorScheme = "auto"
defaultAppearance = "dark"
autoSwitchAppearance = true

mainSections = ["posts"]

showReadingTime = true
enableCodeCopy = true

[homepage]
  layout = "background"
  homepageImage = "gear_background.png"
  logo = "owl_logo.png"


  title = "LithyLabs"
  subtitle = "Thoughts on software, games, and systems"

  showRecent = true
  recentLimit = 5

[article]
  showComments = true

[comments]
  enabled = true
  provider = "giscus"

[comments.giscus]
  repo = "lithylabs/lithylabs.github.io"
  repoId = "R_kgDOQ6my_w"
  category = "General"
  categoryId = "DIC_kwDOQ6my_84C1C4v"
  mapping = "pathname"
  strict = "1"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  theme = "preferred_color_scheme"
  lang = "en"